version: '3'
services:
    haskell:
        build: .
        tty: true
        stdin_open: true
        volumes:
            - ./src:/project
        ports:
            - "8888:8888"

# use docker-compose run haskell
